# Generated by Django 6.0.6 on 2026-07-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_subrolemaster_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20)),
                ('total_fuel_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_collection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('BALANCED', 'Balanced'), ('SHORT', 'Cash Short'), ('EXCESS', 'Cash Excess')], default='BALANCED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to='user.usermaster')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='user.usermaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_receipts', to='user.usermaster')),
            ],
            options={
                'db_table': 'petrotrack_receipt_master',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='receipt.receiptmaster')),
            ],
            options={
                'db_table': 'petrotrack_receipt_expense',
            },
        ),
        migrations.CreateModel(
            name='ReceiptDenomination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_500', models.PositiveIntegerField(default=0)),
                ('note_200', models.PositiveIntegerField(default=0)),
                ('note_100', models.PositiveIntegerField(default=0)),
                ('note_50', models.PositiveIntegerField(default=0)),
                ('note_20', models.PositiveIntegerField(default=0)),
                ('note_10', models.PositiveIntegerField(default=0)),
                ('coins', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='denomination', to='receipt.receiptmaster')),
            ],
            options={
                'db_table': 'petrotrack_receipt_denomination',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_collection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='receipt.receiptmaster')),
            ],
            options={
                'db_table': 'petrotrack_receipt_collection',
            },
        ),
        migrations.CreateModel(
            name='ReceiptFuelSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=20)),
                ('opening_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('testing_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_per_liter', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sales', to='receipt.receiptmaster')),
            ],
            options={
                'db_table': 'petrotrack_receipt_fuel_sale',
                'unique_together': {('receipt', 'fuel_type')},
            },
        ),
    ]
