# Generated by Django 6.0.6 on 2026-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstationmaster',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
