# Generated by Django 6.0.6 on 2026-07-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fuelstationmaster_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
