# Generated by Django 6.0.6 on 2026-07-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermaster_supabase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrolemaster',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_roles', to='user.rolemaster'),
        ),
    ]
