# Generated by Django 6.0.6 on 2026-07-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscriptionplanmaster_fuelstationsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelstationsubscription',
            new_name='petrotrack__fuel_st_2d576d_idx',
            old_name='petrotrack__fuel_s_32d78b_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelstationsubscription',
            new_name='petrotrack__end_dat_c7d720_idx',
            old_name='petrotrack__end_dat_1d6b80_idx',
        ),
    ]
