# Generated by Django 6.0.6 on 2026-07-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_petrotrack__fuel_s_32d78b_idx_petrotrack__fuel_st_2d576d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemaster',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
